FROM ubuntu:18.04 

RUN apt-get update && apt-get install -yqq \
      curl \
      wget \
      gpg \
      apt-transport-https \
      software-properties-common \
      git \
    && add-apt-repository -y ppa:deadsnakes/ppa \ 
    && apt-get install -yqq \
      python3.8 \
      python3.8-distutils 

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

RUN wget https://bootstrap.pypa.io/get-pip.py \
    && python3.8 get-pip.py \
    && python3.8 -m pip install --upgrade pip && python3.8 -m pip install mediapipe

RUN python3.8 -m pip install opencv-python

RUN rm -rf /var/lib/apt/lists/*

CMD ["bash"]