FROM ubuntu:18.04 

RUN apt-get update && apt-get install -yqq \
      curl \
      gpg \
      apt-transport-https \
      software-properties-common \
      git \
    && \
    add-apt-repository -y ppa:deadsnakes/ppa &&\
    apt-get install -yqq \
    python3.8 \
    python3-pip \
    && \
    python3 -m pip install --upgrade pip && python3 -m pip install mediapipe\
    && rm -rf /var/lib/apt/lists/*


CMD ["bash"]